length_in_x: 4.0
length_in_y: 2.5
# length_in_x: 8.0
# length_in_y: 6.0
position_x: 0.0
position_y: 0.0
resolution: 0.05
min_variance: 0.0001
max_variance: 0.001
mahalanobis_distance_threshold: 20
multi_height_noise: 0.00001