input_sources:
  lidar: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /filtered_cloud/depth/output
    # topic: /crop_box/map_bias/output
    queue_size: 1
    publish_on_update: true # Whether to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect


map_frame_id: "cavity"
robot_base_frame_id: "base_link"
robot_pose_with_covariance_topic: "" # Leaving this empty skipps pose covariance updates.
robot_pose_cache_size: 200
track_point_frame_id: "cavity"
track_point_x: 0.0
track_point_y: 1.25
# track_point_x: 1.5
# track_point_y: 2.5
track_point_z: 0.0